# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6fe642c3b645dd3db36680a6ce6954f87111b41a4116bfc0491977fde822e7ceaebfa4eaac2ac41ece0c7376daf66c6fbf9382db373aafadb710bdb73d94ce9

test:
  secret_key_base: c00192fe32319efdb492bf334035dcb9bce5c3d892571214740f0453c8618b80c3cbfe18c55aeab82550371749f9d8c7c2d155b85f545fbfc5e0703289fdde02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
